### ISSUE TITLE
Failed Build on OpenBSD6.5-current/amd6.4 failed with error: 'se of undeclared identifier 'SYSCONFDIR'    path = SYSCONFDIR "/" PROXYCHAINS_CONF_FILE; '

### ISSUE THREAD

**Issue by herme-s** [haad/proxychains#89]
**Step To reproduce Below from home dir :**
`$ doas git clone https://github.com/haad/proxychains.git
  $ doas  ./configure
  $ doas make && make install`

`cc -O2 -pipe   -c src/core.c
  cc -O2 -pipe   -c src/common.c
  src/common.c:41:9: error: use of undeclared identifier 'SYSCONFDIR'
        path = SYSCONFDIR "/" PROXYCHAINS_CONF_FILE;
               ^
1 error generated.
*** Error 1 in /home/herme-s/git-repos/proxychains (<sys.mk>:87 'src/common.o')`
