### ISSUE TITLE
build on OpenBSD 5.6 fails with 'error: 'AI_V4MAPPED' undeclared (first use in this function)'

### ISSUE THREAD

**Issue by sysfu** [haad/proxychains#46]
Steps to reproduce

$ sudo git clone https://github.com/haad/proxychains.git
$ cd proxychains/
$ sudo ./configure 
$ sudo gmake
cc -Wall -O2 -g -std=c99 -D_GNU_SOURCE -pipe -DTHREAD_SAFE -Werror   -DLIB_DIR=\"/usr/local/lib\" -DINSTALL_PREFIX=\"/usr/local\" -DDLL_NAME=\"libproxychains4.so\" -DSYSCONFDIR=\"/usr/local/etc\"  -fPIC -c -o src/core.o src/core.c
src/core.c:40: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'internal_ips_lock'
src/core.c: In function 'proxy_getaddrinfo':
src/core.c:912: error: 'AI_V4MAPPED' undeclared (first use in this function)
src/core.c:912: error: (Each undeclared identifier is reported only once
src/core.c:912: error: for each function it appears in.)
Makefile:63: recipe for target 'src/core.o' failed
gmake: *** [src/core.o] Error 1

**Comment by sysfu** [comment]
I was able to get past the parse error by adding CFLAGS='-pthreads'  to the end of the config.mak file.

Now it fails with this error message when running make:

# make
cc -O2 -pipe   -c src/core.c
src/core.c: In function 'proxy_getaddrinfo':
src/core.c:912: error: 'AI_V4MAPPED' undeclared (first use in this function)
src/core.c:912: error: (Each undeclared identifier is reported only once
src/core.c:912: error: for each function it appears in.)
*** Error 1 in /usr/local/src/proxychains (<sys.mk>:87 'src/core.o')

**Comment by sysfu** [comment]
Make command also fails on FreeBSD 9x

# make
"Makefile", line 31: Need an operator
Error expanding embedded variable.

**Comment by sysfu** [comment]
This issue has been fixed in proxychains-ng with [this commit] (https://github.com/rofl0r/proxychains-ng/commit/7b962a4ca3b4c8446fe5d238ad1778586d82ef7f)
